/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modulo2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author mario
 */
public class v2parcial extends javax.swing.JFrame {

    /**
     * Creates new form v2parcial
     */
    public v2parcial() {
        initComponents();
    }

    // 1. Lista global para almacenar procesos
    private List<String[]> processList = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelProcess = new javax.swing.JLabel();
        jLabelNo = new javax.swing.JLabel();
        jTextFieldNo = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelSize = new javax.swing.JLabel();
        jTextFieldSize = new javax.swing.JTextField();
        jLabelPriority = new javax.swing.JLabel();
        jTextFieldPriority = new javax.swing.JTextField();
        jButtonAddProcess = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonSortByPriority = new javax.swing.JButton();
        jButtonSortBySize = new javax.swing.JButton();
        jButtonSortByNo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProcess = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("Spool ADMINISTRADOR");

        jLabelProcess.setText("Proceso");

        jLabelNo.setText("No.");

        jLabelName.setText("Nombre");

        jLabelSize.setText("Tamaño");

        jLabelPriority.setText("Prioridad");

        jButtonAddProcess.setText("Ingresar Proceso");
        jButtonAddProcess.setToolTipText("");
        jButtonAddProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProcessActionPerformed(evt);
            }
        });

        jLabel7.setText("_________________________________________________________________________________________________");

        jButtonSortByPriority.setText("PRIORIDAD");
        jButtonSortByPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortByPriorityActionPerformed(evt);
            }
        });

        jButtonSortBySize.setText("TAMAÑO");
        jButtonSortBySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortBySizeActionPerformed(evt);
            }
        });

        jButtonSortByNo.setText("ENTRADA");
        jButtonSortByNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortByNoActionPerformed(evt);
            }
        });

        jTextAreaProcess.setColumns(20);
        jTextAreaProcess.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProcess);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(jButtonSortByPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(jButtonSortBySize, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonSortByNo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextFieldNo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jButtonAddProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabelPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabelTitle)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProcess)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNo)
                                        .addComponent(jTextFieldNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelName)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelSize)
                                        .addComponent(jTextFieldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPriority)
                                        .addComponent(jTextFieldPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddProcess)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonSortByPriority)
                                        .addComponent(jButtonSortBySize)
                                        .addComponent(jButtonSortByNo))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButtonAddProcessActionPerformed(java.awt.event.ActionEvent evt) {
        // 2. Obtener datos de los campos de texto
        String no = jTextFieldNo.getText();
        String name = jTextFieldName.getText();
        String size = jTextFieldSize.getText();
        String priority = jTextFieldPriority.getText();

        // 3. Crear registro de proceso y añadir a la lista
        String[] process = new String[4];
        process[0] = no;
        process[1] = name;
        process[2] = size;
        process[3] = priority;

        processList.add(process);

        // Limpiar campos de texto
        jTextFieldNo.setText("");
        jTextFieldName.setText("");
        jTextFieldSize.setText("");
        jTextFieldPriority.setText("");

        // Actualizar textarea
        displayProcesses();
    }

    private void jButtonSortByPriorityActionPerformed(java.awt.event.ActionEvent evt) {
        // 4. Ordenar por prioridad (mayor prioridad primero)
        Collections.sort(processList, new Comparator<String[]>() {
            public int compare(String[] p1, String[] p2) {
                int priority1 = Integer.parseInt(p1[3]);
                int priority2 = Integer.parseInt(p2[3]);
                // Para mayor prioridad primero
                return Integer.compare(priority2, priority1);
            }
        });
        displayProcesses();
    }

    private void jButtonSortBySizeActionPerformed(java.awt.event.ActionEvent evt) {
        // 5. Ordenar por tamaño (mayor tamaño primero)
        Collections.sort(processList, new Comparator<String[]>() {
            public int compare(String[] p1, String[] p2) {
                int size1 = Integer.parseInt(p1[2]);
                int size2 = Integer.parseInt(p2[2]);
                // Para mayor tamaño primero
                return Integer.compare(size2, size1);
            }
        });
        displayProcesses();
    }

    private void jButtonSortByNoActionPerformed(java.awt.event.ActionEvent evt) {
        // 6. Ordenar por número de entrada (No.)
        Collections.sort(processList, new Comparator<String[]>() {
            public int compare(String[] p1, String[] p2) {
                int no1 = Integer.parseInt(p1[0]);
                int no2 = Integer.parseInt(p2[0]);
                return Integer.compare(no1, no2);
            }
        });
        displayProcesses();
    }

    private void displayProcesses() {
        // 7. Mostrar procesos en el textarea
        StringBuilder sb = new StringBuilder();
        sb.append("No.\tNombre\tTamaño\tPrioridad\n");
        for (String[] process : processList) {
            sb.append(process[0]).append("\t")
                    .append(process[1]).append("\t")
                    .append(process[2]).append("\t")
                    .append(process[3]).append("\n");
        }
        jTextAreaProcess.setText(sb.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v2parcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v2parcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v2parcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v2parcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v2parcial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonAddProcess;
    private javax.swing.JButton jButtonSortByNo;
    private javax.swing.JButton jButtonSortByPriority;
    private javax.swing.JButton jButtonSortBySize;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNo;
    private javax.swing.JLabel jLabelPriority;
    private javax.swing.JLabel jLabelProcess;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaProcess;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNo;
    private javax.swing.JTextField jTextFieldPriority;
    private javax.swing.JTextField jTextFieldSize;
    // End of variables declaration
}
