/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modulo3;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author mario
 */
public class vMemoryCapacity extends javax.swing.JFrame {

    /**
     * Creates new form vMemoryCapacity
     */
    private int availableMemory = 100;
    private DefaultListModel<String> processListModel;

    public vMemoryCapacity() {
        initComponents();
        processListModel = new DefaultListModel<>();
        jListProcessList.setModel(processListModel);
        jTextFieldAvailableSize.setText(availableMemory + "/100");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextFieldNameProcess = new javax.swing.JTextField();
        jLabelNameProcess = new javax.swing.JLabel();
        jLabelSizeProcess = new javax.swing.JLabel();
        jTextFieldSizeProcess = new javax.swing.JTextField();
        jButtonSaveProcess = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProcessList = new javax.swing.JList<>();
        jTextFieldAvailableSize = new javax.swing.JTextField();
        jLabelAvailbleSize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNameProcess.setText("Nombre del Proceso:");

        jLabelSizeProcess.setText("Tamaño del proceso:");

        jButtonSaveProcess.setText("Guardar");
        jButtonSaveProcess.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonSaveProcessActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListProcessList);

        jTextFieldAvailableSize.setEditable(false);

        jLabelAvailbleSize.setText("Memoria Disponible:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelNameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldNameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldSizeProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jButtonSaveProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(146, 146, 146)
                                                .addComponent(jLabelSizeProcess)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelAvailbleSize)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldAvailableSize, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNameProcess)
                                        .addComponent(jLabelSizeProcess))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldNameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSizeProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonSaveProcess))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldAvailableSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelAvailbleSize))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>

    private void jButtonSaveProcessActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String processName = jTextFieldNameProcess.getText();
        int processSize;

        try {
            processSize = Integer.parseInt(jTextFieldSizeProcess.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El tamaño del proceso debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (processSize > availableMemory) {
            JOptionPane.showMessageDialog(this, "No hay memoria disponible suficiente para realizar el registro.", "Memoria Insuficiente", JOptionPane.WARNING_MESSAGE);
        } else {
            availableMemory -= processSize;
            processListModel.addElement(processName + " - Tamaño: " + processSize);
            jTextFieldAvailableSize.setText(availableMemory + "/100");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vMemoryCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vMemoryCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vMemoryCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vMemoryCapacity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vMemoryCapacity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonSaveProcess;
    private javax.swing.JLabel jLabelAvailbleSize;
    private javax.swing.JLabel jLabelNameProcess;
    private javax.swing.JLabel jLabelSizeProcess;
    private javax.swing.JList<String> jListProcessList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAvailableSize;
    private javax.swing.JTextField jTextFieldNameProcess;
    private javax.swing.JTextField jTextFieldSizeProcess;
    // End of variables declaration
}
